server:
  port: 61070

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:byh9811/config_example.git
          default-label: main
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIDxujNif21U8pF28SibSpAFmNv5yYFiSbgi7hpjaootBoAoGCCqGSM49
            AwEHoUQDQgAE4fgXrmggSin3JeSz/cd6yG05W4bcokLoMRMJYeXM9ZqNQzlbdhiE
            5nG1mYZ51kwqKfLLdEwkrWQ9EyD9MbjtOw==
            -----END EC PRIVATE KEY-----
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256
          search-paths: "{application}"
        encrypt:
          enabled: false

# actuator ??
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

encrypt:
  key: ${ssh-encrypt-key}