server:
  port: 61070

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:byh9811/config_example.git
          default-label: main
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIFKQkHjt9k+EZN2ObHJpqKyBdvT1YG4DnhucqR863U53oAoGCCqGSM49
            AwEHoUQDQgAEeGJnUOomW3bRqtW/05A5TPry3ogznsaAMARE3SZimM1RJnwc0lZM
            3Nye6LiF3zx476wUovGDmbsGV6ZAsDRtRQ==
            -----END EC PRIVATE KEY-----
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256
          search-paths: "{application}"
        encrypt:
          enabled: false

# actuator ??
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

encrypt:
  key: ${ssh-encrypt-key}