spring:
  config:
    import: "optional:configserver:https://ssok.site" #config server uri
  cloud:
    config:
      name: config
      profile: local
      label: idcard

encrypt:
  key: ${ssh-encrypt-key}