spring:
  config:
    import: "optional:configserver:https://ssok.site" #config server uri
  cloud:
    config:
      name: config
      profile: pocket
#      profile: { 도메인 이름 }

encrypt:
  key: ${ssh-encrypt-key}
