server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/ssok_namecard?useUnicode=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ssoknamecardid
    password: ssoknamecardpw
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true
    defer-datasource-initialization: true