spring:
  config:
#    import: "optional:configserver:{Config 서버 IP}:{포트}" #config server uri
    import: optional:configserver:http://localhost:61070 #config server uri
  cloud:
    config:
      name: test
#      name: { 도메인 이름 }
      profile: test

encrypt:
  key: ${ssh-encrypt-key}
